### ISSUE TITLE
Source links

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-v01#43]
The source link on this page - https://ml5js.org/docs/simple-image-classification-example.html -isn't right. @cvalenzuela I'm happy to fix some of these things but not 100% sure best way as #37 is still waiting to be merged?

(Thanks @AlcaDesign for noting this!)

**Comment by AlcaDesign** [comment]
There's a lot of text that says "deeplearn.js" instead of "tenserflow.js," and missing periods at the end of sentences. Other than that, here's some more broken links, (minor) automatically redirected links, specific grammar mistakes, missing links, etc.



### Documentation



* On the ["Getting Started"](https://ml5js.org/docs/getting-started.html) **docs** page:

  * *(Minor)* the "latest version" link is redirected from `https://github.com/ITPNYU/ml5` to `https://github.com/ml5js/ml5-library` automatically.

  * *(Minor)* the "ml5.min.js" link is redirected from `https://github.com/ITPNYU/ml5/tree/master/dist` to `https://github.com/ml5js/ml5-library/tree/master/dist` automatically.



* On the ["Image Classifier"](https://ml5js.org/docs/imageclassifier.html) **docs** page:

  * the "SqueezeNet," "MobileNet," and "original SqueezNet model" links are broken.



* On the ["KNN Image Classifier"](https://ml5js.org/docs/knnImage.html) **docs** page:

  * the "ImageClassifier" link is broken.

  * *(Minor)* the "deeplearn.js KNN image classifier model" link is redirected from `https://github.com/PAIR-code/deeplearnjs/tree/master/models/knn_image_classifier` to `https://github.com/tensorflow/tfjs-core/tree/master/models/knn_image_classifier` automatically.

  * the "Source" link is broken.



* On the ["LSTM"](https://ml5js.org/docs/lstm.html) **docs** page:

  * the "this set of pretrained models" link is broken.

  * a grammar error in that same sentence: "used" instead of "use."

  * the "Source" link is broken.



* On the ["Style Transfer"](https://ml5js.org/docs/style-transfer.html) **docs** page:

  * the "this tutorial" link is self-referential, basically broken.

  * *(Minor)* the "this demo" link is redirected from `https://github.com/PAIR-code/deeplearnjs/tree/0608feadbd897bca6ec7abf3340515fe5f2de1c2/demos/fast-style-transfer` to `https://github.com/tensorflow/tfjs-core/tree/0608feadbd897bca6ec7abf3340515fe5f2de1c2/demos/fast-style-transfer` automatically.



* On the ["Word2Vec"](https://ml5js.org/docs/word2vec.html) **docs** page:

  * the "this tutorial" link is self-referential, basically broken.

  * *(Minor)* the "Source" link is redirected from `https://github.com/ITPNYU/ml5/blob/master/src/Word2vec/index.js` to `https://github.com/ml5js/ml5-library/blob/master/src/Word2vec/index.js` automatically.



### Examples



* All other examples *except* "Multiple Image Classification"



* On the ["Train a LSTM"](https://ml5js.org/docs/training-lstm.html) example page:

  * the "this tutorial" link is self-referential, basically broken.



* On the ["LSTM Interactive"](https://ml5js.org/docs/lstm-interactive-example.html) example page:

  * the "this tutorial" link is self-referential, basically broken.



* On the ["Style Transfer"](https://ml5js.org/docs/style-transfer-image-example.html) example page:

  * the "this tutorial" link is self-referential, basically broken.

  * the "Udnie (Young American Girl, The Dance), 1913 - Francis Picabia" link is the same as the previous link, which is incorrect.



* On the ["Style Transfer with Webcam"](https://ml5js.org/docs/style-transfer-webcam-example.html) example page:

  * the "this tutorial" link is self-referential, basically broken.

  * the "Udnie (Young American Girl, The Dance), 1913 - Francis Picabia" text is not linked.



### Datasets



* On the ["Making Your Own Datasets"](https://ml5js.org/docs/making-datasets.html) example page:

  * *(Minor)* the "OpenCV" link can be `https` but isn't.



### Training Models



* On the ["Style Transfer"](https://ml5js.org/docs/training-setup.html) example page:

  * the "deeplearn.js" and "ml5.js" links is missing its `href` value, basically broken.



* On the ["Train a LSTM"](https://ml5js.org/docs/training-lstm.html) **training models** page:

  * *(Minor)* the "deeplearn.js" link is redirected from `https://github.com/PAIR-code/deeplearnjs` to `https://github.com/tensorflow/tfjs-core` automatically.

  * *(Minor)* the "ml5.js" text is not linked.

  * the "More detailed instructions here" link is directed to the homepage instead of the "Python Setup" page.

**Comment by cvalenzuela** [comment]
All solved! See https://github.com/ml5js/ml5-website/pull/47
